-- Flatten "additional_profile" JSON into a readable table-like view for Supabase.
CREATE OR REPLACE VIEW public.profile_additional_fields AS
SELECT
  p.id AS profile_id,
  p.email,
  p.preferred_name,
  p.updated_at,
  p.additional_profile ->> 'degree' AS degree,
  p.additional_profile ->> 'schoolAttendanceReasons' AS school_attendance_reasons,
  p.additional_profile ->> 'schoolAttendanceOtherReason' AS school_attendance_other_reason,
  p.additional_profile ->> 'seminarLaboratory' AS seminar_laboratory,
  p.additional_profile ->> 'researchTheme' AS research_theme,
  p.additional_profile ->> 'schoolClubActivity' AS school_club_activity,
  p.additional_profile ->> 'schoolLifeExperience1' AS school_life_experience_1,
  p.additional_profile ->> 'schoolLifeExperience2' AS school_life_experience_2,
  p.additional_profile ->> 'otherEducationSchool1' AS other_education_school_1,
  p.additional_profile ->> 'otherEducationDepartment1' AS other_education_department_1,
  p.additional_profile ->> 'otherEducationAdmission1' AS other_education_admission_1,
  p.additional_profile ->> 'otherEducationGraduation1' AS other_education_graduation_1,
  p.additional_profile ->> 'otherEducationSchool2' AS other_education_school_2,
  p.additional_profile ->> 'otherEducationDepartment2' AS other_education_department_2,
  p.additional_profile ->> 'otherEducationAdmission2' AS other_education_admission_2,
  p.additional_profile ->> 'otherEducationGraduation2' AS other_education_graduation_2,
  p.additional_profile ->> 'overseasExperience' AS overseas_experience,
  p.additional_profile ->> 'overseasCountry1' AS overseas_country_1,
  p.additional_profile ->> 'overseasReason1' AS overseas_reason_1,
  p.additional_profile ->> 'overseasPeriod1Start' AS overseas_period_1_start,
  p.additional_profile ->> 'overseasPeriod1End' AS overseas_period_1_end,
  p.additional_profile ->> 'overseasCountry2' AS overseas_country_2,
  p.additional_profile ->> 'overseasReason2' AS overseas_reason_2,
  p.additional_profile ->> 'overseasPeriod2Start' AS overseas_period_2_start,
  p.additional_profile ->> 'overseasPeriod2End' AS overseas_period_2_end,
  p.additional_profile ->> 'overseasCountry3' AS overseas_country_3,
  p.additional_profile ->> 'overseasReason3' AS overseas_reason_3,
  p.additional_profile ->> 'overseasPeriod3Start' AS overseas_period_3_start,
  p.additional_profile ->> 'overseasPeriod3End' AS overseas_period_3_end,
  p.additional_profile ->> 'overseasOtherExperience' AS overseas_other_experience,
  p.additional_profile ->> 'hospitalizedTwoWeeks' AS hospitalized_two_weeks,
  p.additional_profile ->> 'workConsiderations' AS work_considerations,
  p.additional_profile ->> 'englishAbility' AS english_ability,
  p.additional_profile ->> 'toeicScore' AS toeic_score,
  p.additional_profile ->> 'toeicScoreCertificate' AS toeic_score_certificate,
  p.additional_profile ->> 'toeflIbtScore' AS toefl_ibt_score,
  p.additional_profile ->> 'toeflCbtScore' AS toefl_cbt_score,
  p.additional_profile ->> 'toeflItpScore' AS toefl_itp_score,
  p.additional_profile ->> 'ieltsScore' AS ielts_score,
  p.additional_profile ->> 'languageOtherScores' AS language_other_scores,
  p.additional_profile ->> 'licensesCertifications' AS licenses_certifications,
  p.additional_profile ->> 'driverLicense' AS driver_license,
  p.additional_profile ->> 'otherLicensesCertifications' AS other_licenses_certifications,
  p.additional_profile ->> 'awardsRecognition' AS awards_recognition,
  p.additional_profile ->> 'awardsRecognitionDetails' AS awards_recognition_details,
  p.additional_profile ->> 'criminalRecord' AS criminal_record,
  p.additional_profile ->> 'workHistoryCompany1' AS work_history_company_1,
  p.additional_profile ->> 'workHistoryPeriod1Start' AS work_history_period_1_start,
  p.additional_profile ->> 'workHistoryPeriod1End' AS work_history_period_1_end,
  p.additional_profile ->> 'workHistoryEmploymentStatus1' AS work_history_employment_status_1,
  p.additional_profile ->> 'workHistoryResponsibilities1' AS work_history_responsibilities_1,
  p.additional_profile ->> 'workHistoryJobStatus1' AS work_history_job_status_1,
  p.additional_profile ->> 'workHistoryCompany2' AS work_history_company_2,
  p.additional_profile ->> 'workHistoryPeriod2Start' AS work_history_period_2_start,
  p.additional_profile ->> 'workHistoryPeriod2End' AS work_history_period_2_end,
  p.additional_profile ->> 'workHistoryEmploymentStatus2' AS work_history_employment_status_2,
  p.additional_profile ->> 'workHistoryResponsibilities2' AS work_history_responsibilities_2,
  p.additional_profile ->> 'workHistoryJobStatus2' AS work_history_job_status_2,
  p.additional_profile ->> 'workHistoryOther' AS work_history_other,
  p.additional_profile ->> 'highSchool' AS high_school,
  p.additional_profile ->> 'highSchoolGraduationDate' AS high_school_graduation_date,
  p.additional_profile ->> 'highSchoolGapReasons' AS high_school_gap_reasons,
  p.additional_profile ->> 'highSchoolGapOther' AS high_school_gap_other,
  p.additional_profile ->> 'latestAcademicAdmissionDate' AS latest_academic_admission_date,
  p.additional_profile ->> 'latestAcademicOverseasSchool' AS latest_academic_overseas_school,
  p.additional_profile ->> 'latestAcademicUniversityLocation' AS latest_academic_university_location,
  p.additional_profile ->> 'latestAcademicUniversityLocationOther' AS latest_academic_university_location_other,
  p.additional_profile ->> 'latestAcademicUniversityName' AS latest_academic_university_name,
  p.additional_profile ->> 'latestAcademicUniversityNameOther' AS latest_academic_university_name_other,
  p.additional_profile ->> 'latestAcademicDepartmentName' AS latest_academic_department_name,
  p.additional_profile ->> 'latestAcademicDepartmentNameOther' AS latest_academic_department_name_other,
  p.additional_profile ->> 'nationalityPrimary' AS nationality_primary,
  p.additional_profile ->> 'nationalitySecondary' AS nationality_secondary,
  p.additional_profile ->> 'reasonForEntry' AS reason_for_entry,
  p.additional_profile ->> 'vacationAddressSameAsCurrent' AS vacation_address_same_as_current,
  p.additional_profile ->> 'vacationPostalCode' AS vacation_postal_code,
  p.additional_profile ->> 'vacationPrefecture' AS vacation_prefecture,
  p.additional_profile ->> 'vacationAddressLine1' AS vacation_address_line1,
  p.additional_profile ->> 'vacationAddressLine2' AS vacation_address_line2,
  p.additional_profile ->> 'vacationPhone' AS vacation_phone
FROM public.profiles p;
